theme: jekyll-theme-minimal
title: Project RemontAda : A Bee(r)xpert
description: Website for the project of ADA course, group RemontADA
show_downloads: True
navigation:
  - title: Test
    url: test

