theme: jekyll-theme-minimal
title: A Beer(x)pert
description: Project of Laaroussi Yannis, Palmisano Fabio, Roduit Vincent, Roh Vincent, Semiz Alexi
show_downloads: True
navigation:
  - title : Analysis
    url : textanalysis

