theme: jekyll-theme-minimal
title: A Beerxpert
description: Website for the project of ADA course, group RemontADA
show_downloads: True
navigation:
  - title: Test
    url: test
  - title : Text Analysis
    url : textanalysis

